### ISSUE TITLE
mac_address in docker compose ignored

### ISSUE THREAD

**Issue by isegals** [OpenMediaVault-Plugin-Developers/openmediavault-compose#25]
Hello, mac_address in docker compose seems to be ignored, but mac-address via docker run works fine.
Example: 
```
version: '3.0'
services:
  xeoma:
    container_name: xeoma
    image: coppit/xeoma
    restart: on-failure
    hostname: xeoma
    mac_address: 08:ae:ef:44:26:59 
    ports:
      - "8097:8090"
      - "10097:10090"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/xeoma/config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/xeoma/archive-cache:/archive-cache
      - /mnt/ssd/tmp/xeoma/archive:/archive 
    environment: 
      - VERSION=https://felenasoft.com/xeoma/downloads/2023-08-10/linux/xeoma_linux64.tgz
      - PASSWORD="admin"
```

```
docker run --name=xeoma \
  -d \
  -p 8097:8090 \
  -p 10097:10090 \
  -v /local/xeoma/config:/config \
  -v /local/xeoma/archive:/archive \
  -e VERSION=https://felenasoft.com/xeoma/downloads/2023-08-10/linux/xeoma_linux64.tgz \
  -e PASSWORD=admin \
  --hostname=xeoma \
  --mac-address 08:ae:ef:44:26:59 \
  --restart on-failure \
  coppit/xeoma
```
