### ISSUE TITLE
Feature request: Store labels using compose.override.yml file.

### ISSUE THREAD

**Issue by jumkey** [OpenMediaVault-Plugin-Developers/openmediavault-compose#28]
It would be great if labels could be edited independently and stored in compose.override.yml.
e.g. compose.override.yml
```yaml
services:
  jellyfin:
    labels:
      # for unraid
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: 'http://[IP]:[PORT:8096]'
      net.unraid.docker.shell: ''
      # for homepage
      homepage.description: CHANGE_TO_COMPOSE_DESCRIPTION
      homepage.group: Media
      homepage.href: http://openmediavault.local:8096/
      homepage.icon: jellyfin.svg
      homepage.name: CHANGE_TO_COMPOSE_NAME
      # for openmediavault compose? from https://github.com/OpenMediaVault-Plugin-Developers/packages/blob/master/compose-files/jellyfin/compose.override.yml
      org.openmediavault.compose.icon: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyfin.svg'
      org.openmediavault.compose.webui: 'http://[IP]:[PORT:8096]'
      org.openmediavault.compose.shell: 'bash'
      org.openmediavault.compose.abc: ''
      org.openmediavault.compose.xyz: ''

  redis:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
```

In the example, I made some assumptions about the future marketplace, including support for `icon` `webui` and  attach `shell`.
labels that are not related to the main file are also stored separately here.

Others
Personally, I prefer convention over configuration.
Consider using
$name.yml->compose.yml/docker-compose.yml
$name.env->.env
compose.override.yml/docker-compose.override.yml

For instance, using `- .env` makes it unnecessary to consider whether the name is `immich`.
https://github.com/OpenMediaVault-Plugin-Developers/packages/blob/33aa9b6d487cd674c15d8f584dcc832894ba6c42/compose-files/immich/immich.yml#L10
