### ISSUE TITLE
Update docker-compose file failed

### ISSUE THREAD

**Issue by realabertian** [OpenMediaVault-Plugin-Developers/openmediavault-compose#31]
```
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-487e3e80-cf7a-45c7-8f3d-a8c201aada61/docker-compose/komga/komga.yml' --file "/srv/dev-disk-by-uuid-487e3e80-cf7a-45c7-8f3d-a8c201aada61/docker-compose/komga/compose.override.yml" --env-file '/srv/dev-disk-by-uuid-487e3e80-cf7a-45c7-8f3d-a8c201aada61/docker-compose/komga/komga.env' --env-file '/srv/dev-disk-by-uuid-487e3e80-cf7a-45c7-8f3d-a8c201aada61/docker-compose/global.env' up -d  2>&1': project name can't be empty. Use `--project-name` to set a valid name in /usr/share/openmediavault/engined/rpc/compose.inc:893
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(622): OMVRpcServiceCompose->{closure}()
#1 /usr/share/openmediavault/engined/rpc/compose.inc(860): OMV\Rpc\ServiceAbstract->execBgProc()
#2 [internal function]: OMVRpcServiceCompose->doCommand()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#5 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#6 {main}
```

It seems that it need to explicitly add --project-name 'your project name' for the command to execute successfully

**Comment by ryecoaaron** [comment]
Without seeing your compose file, all I can guess is that you don't have a project name in the compose file.
https://docs.docker.com/reference/compose-file/version-and-name/

**Comment by realabertian** [comment]
> Without seeing your compose file, all I can guess is that you don't have a project name in the compose file. https://docs.docker.com/reference/compose-file/version-and-name/
```
name: komga
version: '3.3'
services:
  komga:
    image: gotson/komga:1.14.0
    container_name: komga
    volumes:
      - type: bind
        source: /srv/dev-disk-by-uuid-487e3e80-cf7a-45c7-8f3d-a8c201aada61/datahouse/komga/config
        target: /config
      - type: bind
        source: /srv/dev-disk-by-uuid-487e3e80-cf7a-45c7-8f3d-a8c201aada61/datahouse/komga/data
        target: /data
      - type: bind
        source: /etc/timezone #alternatively you can use a TZ environment variable, like TZ=Europe/London
        target: /etc/timezone
        read_only: true
    ports:
      - 9009:25600
    user: "1000:100"
    # remove the whole environment section if you don't need it
    restart: unless-stopped
```
