### ISSUE TITLE
Backup script doesn't save build files

### ISSUE THREAD

**Issue by DonkeeeyKong** [OpenMediaVault-Plugin-Developers/openmediavault-compose#68]
Here is the separate issue, [you asked for](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/issues/66#issuecomment-2988787101):
I have a compose file, that references build information like this:
```
services:
  servicename1:
    image: name1
    build: ./docker/servicename1
    pull_policy: build
``` 
The files in the `./docker` folder are not being saved by the backup script. They are necessary for a full backup though, since it's impossible to recreate the images without the build information.

Thanks for all the work and help!
